name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build-latest:

    if: ${{ github.ref == 'refs/heads/master' }}

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image and push
      uses: docker/build-push-action@v4
      with:
         context: .
         push: true
         tags: prezhdarov/vmware-exporter:latest
  
  
  build-version:

    if: ${{ github.ref_type == 'tag' }}
      
    runs-on: ubuntu-latest
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build the Docker image and push
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: prezhdarov/vmware-exporter:${{ github.ref_name }}
