name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release'
        required: true
        default: 'latest'

jobs:
  build:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: make build
        
      - name: Package for Linux
        run: |
          tar -czvf vmware-exporter-linux-amd64.tar.gz vmware-exporter vmware-exporter.service
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            vmware-exporter-linux-amd64.tar.gz
          tag_name: ${{ github.ref_name || inputs.version }}
          name: ${{ github.ref_name || inputs.version }}
          body: |
            VMware Exporter ${{ github.ref_name }}
            Built from ${{ github.sha }}
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/vmware-exporter:${{ github.ref_name || inputs.version }} -t ${{ secrets.DOCKER_HUB_USERNAME }}/vmware-exporter:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vmware-exporter:${{ github.ref_name || inputs.version }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/vmware-exporter:latest